# Generated by Django 3.1.3 on 2020-11-15 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('image', models.TextField(default='')),
                ('articles', models.TextField(default='')),
                ('info', models.TextField(default='')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField(default='')),
                ('create_date', models.TextField(default='')),
                ('last_modified', models.TextField(default='')),
                ('image', models.TextField(default='')),
                ('summary', models.TextField(default='')),
                ('page_views', models.IntegerField(default=0)),
                ('comments', models.TextField(default='')),
                ('author', models.ForeignKey(default='Anonymous', on_delete=django.db.models.deletion.SET_DEFAULT, to='articles.author')),
            ],
        ),
    ]
