# Generated by Django 3.1.3 on 2020-11-11 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=60)),
                ('author_image', models.TextField(default='')),
                ('author_articles', models.TextField(default='')),
                ('author_info', models.TextField(default='')),
                ('author_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(max_length=255)),
                ('article_text', models.TextField(default='')),
                ('article_create_date', models.TextField(default='')),
                ('article_last_modified', models.TextField(default='')),
                ('article_image', models.TextField(default='')),
                ('article_summary', models.TextField(default='')),
                ('article_page_views', models.IntegerField(default=0)),
                ('article_comments', models.TextField(default='')),
                ('article_author', models.ForeignKey(default='Anonymous', on_delete=django.db.models.deletion.SET_DEFAULT, to='article.author')),
            ],
        ),
    ]
