# Generated by Django 3.1.3 on 2020-11-11 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='article_author',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='article_comments',
            new_name='comments',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='article_create_date',
            new_name='create_date',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='article_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='article_last_modified',
            new_name='last_modified',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='article_page_views',
            new_name='page_views',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='article_summary',
            new_name='summary',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='article_text',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='article_title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='author',
            old_name='author_articles',
            new_name='articles',
        ),
        migrations.RenameField(
            model_name='author',
            old_name='author_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='author',
            old_name='author_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='author',
            old_name='author_info',
            new_name='info',
        ),
        migrations.RenameField(
            model_name='author',
            old_name='author_name',
            new_name='name',
        ),
    ]
